title: Jude Haris
description: What I do, my projects, and my thoughts.
theme: minima
url: https://judeharis.github.io
author:
  name: Jude Haris
  email: tbd
social:
  github: judeharis
  # twitter: yourtwitterhandle
  linkedin: https://www.linkedin.com/in/jude-haris/
  email: tbd